### PR TITLE
search 7.x | re-index may be required | LRDOCS-10567

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-10567

Includes
- The upgrade/re-indexing content
- Solr limitations and search results quality

### CODE REVIEW

**Comment by lipusz** [comment]
LGTM. 👍

**Comment by lipusz** [comment]
Maybe we could extend the search results quality with examples where it may be noticable, like language specific sorting.

**Comment by rbohl** [comment]
Sure--what do you mean by language-specific sorting?

**Comment by lipusz** [comment]
https://issues.liferay.com/browse/LPS-152937

**Comment by lipusz** [comment]
Maybe language aware would be a better term

**Comment by lipusz** [comment]
however the ICU docs also says "language specific"

**Comment by rbohl** [comment]
How does this sound? 
> For example, the language aware sorting behavior in Liferay relies on the collation rules present only because of the [ICU Analysis Plugin from Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/plugins/7.x/analysis-icu-collation-keyword-field.html). When searching in Solr some nonoptimal sorting behavior is expected, expecially when field values contain diacritical marks.

**Comment by lipusz** [comment]
Sounds good to me.

**Comment by lipusz** [comment]
Thank you Russell!

**Pull request closed without merging**
