### PR TITLE
search 7.x | elasticsearch installation v. 2 | LRDOCS-7786

### PR DESCRIPTION
**Pull request by rbohl**
https://issues.liferay.com/browse/LRDOCS-7786
I'd like feedback on the edits I've made. I know I still need to 

1. Update the instructions because configurations seem to have changed since I wrote this
~2. Add security to the instructions on setting up Elasticsearch and on configuring Liferay~
3. Run through and test the instructions on 7.3

### CODE REVIEW

**Comment by rbohl** [comment]
No OriginAl available for liferay-learn?

**Comment by rbohl** [comment]
I was wondering if renaming the 3 "reference style" guides would help clarify what the reader will find inside:


| Before | New |
| ------- | ------- |
| Getting Started | Getting Started: Preparing the Servers |
| Installing Elasticsearch | Setting Up Elasticsearch 7 |
| Connecting to Elasticsearch | Connecting Liferay DXP to Elasticsearch 7 |

Let me know what you think.

**Comment by rbohl** [comment]
I just force pushed, including a commit to add security to the Installing Elasticsearch article. I'll begin adding security to the Connector configuration article now (Connecting to Elasticsearch). Let me know if you want me to avoid pushing anything up while you review.

**Comment by lipusz** [comment]
**Started reviewing...** :mag::nerd_face:

**Comment by lipusz** [comment]
> I was wondering if renaming the 3 "reference style" guides would help clarify what the reader will find inside:

What do you mean by "Preparing the Servers"? Preparing DXP and Elasticsearch servers?

**Comment by rbohl** [comment]
> > I was wondering if renaming the 3 "reference style" guides would help clarify what the reader will find inside:
> 
> What do you mean by "Preparing the Servers"? Preparing DXP and Elasticsearch servers?

Well, I meant to indicate that we are preparing the servers that Elasticsearch and DXP will be installed on, but of course, we're only actually preparing the Elasticsearch servers (adding the hosts and increasing the virtual memory in an on-ppremise installation). So maybe the original title is good for that one, which is actually "Getting Started with Elasticsearch".

**Comment by lipusz** [comment]
https://github.com/rbohl/liferay-learn/pull/47

**Pull request closed without merging**
